### ISSUE TITLE
Does this export line do anything? 

### ISSUE THREAD

**Issue by taylorjacklespriggs** [sigopt/sigopt-examples#106]
Commands in docker build are executed in a `sh` subprocess. You cannot change environment variables from a subprocess. I suspect that everything works later because the default environment variables are being used. 
https://github.com/sigopt/sigopt-examples/blob/06f258ed2b7f45e5900649a5b37522fa010ff3b9/orchestrate/apache_spark/orchestrate.yml#L9

**Comment by nakulpathak3** [comment]
Hey, yes. Without the export line, the spark master starts at something like 13878923:7077. It's a string of digits which may be related to the container's ID (I'm guessing). By exporting SPARK_MASTER_HOST=localhost, we consistently start the master at localhost:7077 which helps with starting the slave nodes correctly since they need to be passed in the master's host:port and it also is consistent with the address Spark would start on in a non-docker machine

**Comment by taylorjacklespriggs** [comment]
It may be required, but these variables don't survive past the lines where you define them

**Comment by nakulpathak3** [comment]
https://github.com/sigopt/sigopt-examples/pull/107 removes the exports and the steps that would need the exports so we can close this?

**Comment by taylorjacklespriggs** [comment]
yes
